begin;

create table if not exists pitchai_symphony.github_pr_comment_cursors (
  pr_link_id bigint primary key references pitchai_symphony.task_pr_links(id) on delete cascade,
  task_id uuid not null references public.tasks(id) on delete cascade,
  repo_full_name text not null,
  pr_number integer not null,
  last_seen_at timestamp with time zone,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create table if not exists pitchai_symphony.github_pr_comment_responses (
  id bigint generated by default as identity primary key,
  task_id uuid not null references public.tasks(id) on delete cascade,
  pr_link_id bigint not null references pitchai_symphony.task_pr_links(id) on delete cascade,
  repo_full_name text not null,
  pr_number integer not null,
  comment_kind text not null,
  github_comment_id text not null,
  github_comment_url text,
  author_login text,
  body text not null,
  github_created_at timestamp with time zone not null,
  status text not null default 'pending',
  attempts integer not null default 0,
  next_attempt_at timestamp with time zone not null default now(),
  session_id text,
  thread_id text,
  response_body text,
  response_github_comment_id text,
  response_url text,
  error text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  responded_at timestamp with time zone,
  constraint github_pr_comment_responses_status_check
    check (status in ('pending', 'processing', 'responded', 'failed', 'ignored'))
);

create unique index if not exists github_pr_comment_responses_comment_key_idx
  on pitchai_symphony.github_pr_comment_responses (repo_full_name, pr_number, comment_kind, github_comment_id);

create index if not exists github_pr_comment_responses_pending_idx
  on pitchai_symphony.github_pr_comment_responses (status, next_attempt_at, github_created_at, id);

create index if not exists github_pr_comment_responses_task_idx
  on pitchai_symphony.github_pr_comment_responses (task_id, created_at desc, id desc);

insert into pitchai_symphony.schema_migrations(version, description)
values ('013_pr_review_comment_bridge', 'Track GitHub PR review comments and Codex resume responses')
on conflict (version) do nothing;

commit;
